version: "3.9"

services:
  scylla1:
    image: scylladb/scylla:5.4
    container_name: acecinema-scylla1
    command: >
      --smp 1 --memory 750M --overprovisioned 1
      --api-address 0.0.0.0
      --listen-address scylla1
      --broadcast-address scylla1
      --rpc-address 0.0.0.0
      --broadcast-rpc-address scylla1
      --seeds scylla1,scylla2,scylla3
    volumes:
      - scylla1-data:/var/lib/scylla
    ports:
      - "9042:9042"
      - "10000:10000"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status > /dev/null"]
    networks:
      - acecinema

  scylla2:
    image: scylladb/scylla:5.4
    container_name: acecinema-scylla2
    command: >
      --smp 1 --memory 750M --overprovisioned 1
      --api-address 0.0.0.0
      --listen-address scylla2
      --broadcast-address scylla2
      --rpc-address 0.0.0.0
      --broadcast-rpc-address scylla2
      --seeds scylla1,scylla2,scylla3
    depends_on:
      - scylla1
    volumes:
      - scylla2-data:/var/lib/scylla
    ports:
      - "9142:9042"
      - "11000:10000"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status > /dev/null"]
    networks:
      - acecinema

  scylla3:
    image: scylladb/scylla:5.4
    container_name: acecinema-scylla3
    command: >
      --smp 1 --memory 750M --overprovisioned 1
      --api-address 0.0.0.0
      --listen-address scylla3
      --broadcast-address scylla3
      --rpc-address 0.0.0.0
      --broadcast-rpc-address scylla3
      --seeds scylla1,scylla2,scylla3
    depends_on:
      - scylla1
    volumes:
      - scylla3-data:/var/lib/scylla
    ports:
      - "9242:9042"
      - "12000:10000"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status > /dev/null"]
    networks:
      - acecinema

volumes:
  scylla1-data: {}
  scylla2-data: {}
  scylla3-data: {}

networks:
  acecinema:
    name: acecinema-net
