version: "3.9"

services:
  app:
    image: python:3.11-alpine
    container_name: "api-dijon"    # à ajuster (ex: api-dijon, api-thory)
    environment:
      SITE_NAME: dijon             # à ajuster
      SERVICE_NAME: api            # à ajuster
      PUBLISHED_PORT: 8080         # à ajuster
      TZ: Europe/Paris             # à ajuster
    working_dir: /opt/docker/acecinema/api
    command: >
      sh -c "
        apk add --no-cache wget >/dev/null &&
        cat <<'PY' > /app.py
from http.server import BaseHTTPRequestHandler, HTTPServer
import os
PORT = int(os.getenv('PUBLISHED_PORT','8080'))
SITE = os.getenv('SITE_NAME','site')
SERVICE = os.getenv('SERVICE_NAME','service')
class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/health':
            self.send_response(200); self.end_headers(); self.wfile.write(b'ok')
        else:
            self.send_response(200); self.end_headers(); self.wfile.write(f'service={SERVICE} site={SITE}'.encode())
    def log_message(self, fmt, *args): pass
HTTPServer(('0.0.0.0', PORT), Handler).serve_forever()
PY
        python /app.py
      "
    ports:
      - "8080:8080"                # à ajuster au besoin
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    labels:
      - "site=${SITE_NAME:-dijon}"
      - "service=${SERVICE_NAME:-api}"
